apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: airflow-image
      context: airflow-image

deploy:
  statusCheckDeadlineSeconds: 600 # 10 mins
  helm:
    flags:
      upgrade: ["-i", "--force=false"]
    releases:
    - name: airflow
      chartPath: stable/airflow
      remote: true
      values:
        airflow.image: airflow-image
      valuesFiles: ["helm-charts/stable/airflow/values.yaml", "airflow-image/values.yaml"]
      imageStrategy:
        helm:
          explicitRegistry: false
  kubectl:
    manifests:
      - example-deployment-manifests/*.yaml
      - role-binding/*.yaml
portForward:
  - resourceName: airflow-web
    resourceType: Service
    port: 8080
    localPort: 8080
    namespace: default