apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: airflow-list-deployments
  labels:
    app: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-deployments
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: default